### ISSUE TITLE
Error with brand new Flutter project

### ISSUE THREAD

**Issue by FXschwartz** [jeroen1602/flutter_web_bluetooth#12]
1. Ran `flutter create`
2. Added package to pubspect.yaml
3. Ran application
4. Getting warning

Flutter Doctor output
![image](https://user-images.githubusercontent.com/16527593/141393929-25d83973-88c9-4f82-96b3-1089271e3e51.png)

```
Warning: Operand of null-aware operation '!' has type 'Set<BluetoothDevice>' which excludes null
'Set' is from 'dart:core'.
'BluetoothDevice' is from 'package:flutter_web_bluetooth/src/flutter_web_bluetooth_web.dart' ? _knownDevicesStream.value!
```
![image](https://user-images.githubusercontent.com/16527593/141393874-1da3092d-4913-42fb-a77a-96c2c5f3168c.png)

**Comment by jeroen1602** [comment]
This is a bit of a hack so it can work with rxrxdart version 0.26.0 and 0.27.0.

In the 0.26.0 version that value is null able but in 0.27.0 it isn't so you get the warning.

The library also support 0.26.0 instead of the latest 0.27.0 because the package flutter_blue, a Bluetooth package for Android and iOS, only supports up to 0.26.0 and I want it to be compatible.

But hey wantings are there to be ignored.

**Comment by jeroen1602** [comment]
I've removed RxDart as a dependency all together so it's solved.
