### ISSUE TITLE
Browser supports

### ISSUE THREAD

**Issue by Abhishekvlog** [jeroen1602/flutter_web_bluetooth#62]
### creating a Bluetooth communication web application in flutter. 
I am using flutter_web_bluetooth: ^0.2.1 library for achieve the bluetooth functionality.
* First I enable the Experimental Web Platform Features flag in chrome 
* After enable write code for current browser supports the web bluetooth api. 

## **Issue**
In my chrome Experimental Web Platform Features flag is enable, but when i run the code in flutter after that a new chrome tab is open, in it the browser is showing  browser web bluetooth api support false because the Experimental Web Platform Features flag appears disabled even after enabling the flag . Again i enabled the flag and restarted, And then run the Flutter application and again the flag is disable.
how can i enable this flag?

## **Screenshots/ GIF**
[Screencast from 17-08-23 03:21:57 PM IST.webm](https://github.com/jeroen1602/flutter_web_bluetooth/assets/77963724/03913ee5-368e-45a8-9bd6-2b912da05e45)

**Comment by Abhishekvlog** [comment]
Thank you for the help,
I have created a patch file but I can't enable the experimental flag in browser.

## **Screenshots/ GIF**
[Screencast from 18-08-23 12:32:04 PM IST.webm](https://github.com/jeroen1602/flutter_web_bluetooth/assets/77963724/97f8e512-dd11-4f56-a399-119e616a2178)

could you please help me out

**Comment by jeroen1602** [comment]
It looks like you ran the patch in your own project. But you need to patch your flutter installation.

If you run
```bash
where flutter
```

Then you will get the path where flutter is installed for you. For me it is `/home/jeroen/bin/flutter/bin/flutter`. 
In my case I would need to run the patch from `/home/jeroen/bin/flutter`, the root directory of the flutter installation.

After that don't forget to remove `bin/cache/flutter_tools.snapshot` so that flutter needs to rebuild in order to work.

I hope this helps. You will need to run this patch again after each flutter update. (And update using `flutter upgrade --force` because it will detect changes in your installation)

**Comment by Abhishekvlog** [comment]
@jeroen1602  Thanks for your support.
